import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Mixer</title>
        <link rel="icon" type="image/x-icon" href="./favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Lexend Deca"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Kodchasan"
          rel="stylesheet"
        />
      </head>
      <body class="container" className={inter.className}>
        {children}
      </body>
    </html>
  );
}
